### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by plan5** [plan5/remarvin#7]
# v0.2
- [ ] Add un-/encrypted backup function and offer before setup
- [ ] Add uninstall function
- [ ] Add password change function

# v0.3
- [ ] Allow individual configuration per profile
